### PR TITLE
Replaced `test_motor` w/ `fakeMotionControl`

### PR DESCRIPTION
**Pull request by pattacini**
The plugin `test_motor` has been deprecated.

cc @mfussi66.

### CODE REVIEW

**Comment by mfussi66** [comment]
I think it also needs `fakeRobotConfig.put("allow-deprecated-devices", 1);`, otherwise it quits with an error:
```
[1623682245.250370] [ERROR] /home/mfussi/iit/yarp/src/libYARP_dev/src/yarp/dev/PolyDriver.cpp:321 bool yarp::dev::PolyDriver::coreOpen(yarp::os::Searchable&) (0x000d7051) |yarp.dev.PolyDriver| Device "fakeMotor" is deprecated. Pass the "allow-deprecated-devices" option in the configuration if you want to open it anyway.
```

I just tested the program with the renamed device and the above config option, and everything seems to work fine.

**Comment by pattacini** [comment]
Hi @mfussi66, 
Actually, this PR proposes to use the new device: so it should be all good.

**Comment by traversaro** [comment]
Interestingly, also fakeMotor is deprecated https://github.com/robotology/yarp/pull/2478 . So if `fakeMotionControl` is working fine on YARP 3.4, I would just go for `fakeMotionControl` directly.

**Comment by pattacini** [comment]
Good catch @traversaro 
Let me have a loot at it.

**Comment by pattacini** [comment]
`fakeMotionControl` is not enabled by default in the `robotology-superbuild` and this turns to be problematic for our infrastructure.

I've checked that in https://github.com/orgs/icub-training/packages/container/sandbox/2890684?tag=v2021.05.

I believe we should make it available.

**Comment by pattacini** [comment]
Switched to the use of `fakeMotionControl` device.
To be tested.

**Comment by pattacini** [comment]
Everything's fine 👍🏻 
I've tested it with the latest vvv-school image on Gitpod.

**Pull request merged**
